--- 
abstract: A non-blocking, concurrent DNS server POE component
author: Chris Williams <chris@bingosnet.co.uk>
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: POE-Component-Server-DNS
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp: 0
  Net::DNS: 0.58
  POE: 0.38
  POE::Component::Client::DNS: 1
  POE::Component::Generic: 0.091
  Socket: 0
version: 0.08
